name = "inara-tech-website"
compatibility_date = "2024-09-19"

[env.production]
name = "inara-tech-website"

# Pages configuration
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables (if needed)
# [env.production.vars]
# NODE_ENV = "production"
